version: '3'

services:
  mysql:
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: integration_test
      MYSQL_DATABASE: integration_test
      MYSQL_USER: integration_test
      MYSQL_PASSWORD: integration_test
    ports:
      - 3306:3306

  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: integration_test
      POSTGRES_USER: integration_test
      POSTGRES_PASSWORD: integration_test
    ports:
      - 5432:5432
