dependencies {
    api(libs.spring.beans)
    api(libs.spring.core)
    api(libs.spring.context)
    api(libs.spring.r2dbc)
    api(libs.spring.tx)
    api(libs.spring.boot.starter)
    api(libs.kotlinx.coroutines.core)
    api(libs.kotlinx.coroutines.reactive)
    api(libs.kotlinx.coroutines.reactor)
    api(libs.r2dbc.pool)
    api(project(":komapper-annotation"))
    api(project(":komapper-r2dbc"))
    runtimeOnly(project(":komapper-datetime-r2dbc"))
    runtimeOnly(project(":komapper-template"))
    runtimeOnly(project(":komapper-slf4j"))
    runtimeOnly(project(":komapper-spring-boot-autoconfigure-r2dbc"))
}
