name: Autolabeler

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  autolabeler:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write

    steps:
      - uses: release-drafter/release-drafter/autolabeler@73b95fa1c286dfd6802a4f949b07dad6149f2b0f # v7.5.0
