name: Validate Gradle Wrapper

on: [push, pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
